export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const OPEN_SHOPPING_BAG = 'OPEN_SHOPPING_BAG'
export const CLOSE_SHOPPING_BAG = 'CLOSE_SHOPPING_BAG'
export const ADD_TO_BAG = 'ADD_TO_BAG'
export const INCREMENT_BAG_COUNT = 'INCREMENT_BAG_COUNT'

